config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :categories
  resources :authors
  resources :publishers
  get 'about' => 'about#index'
  root 'books#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  belongs_to :publisher

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
  validates :name, presence: true, length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:edit, :update, :destroy]
  def index
    @authors = Author.all
  end

  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = 'Author Successfully Created!'
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      flash[:notice] = "Author Successfully Updated"
      redirect_to authors_path
    end
  end

  def destroy
    @author.destroy
    flash[:alert] = "Author Removed!"
    redirect_to authors_path
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :show, :destroy]
  def index
    @books = Book.all
    @categories = Category.all
  end

  def new
    @page_title = 'Add New Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book Successfully Created!'
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:notice] = 'Book Successfully Updated'
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  def destroy
    @book.destroy
    flash[:alert] = "Book Removed!"
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year )
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :show, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @page_title = 'Add a New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category successfully created!'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category successfully updated!'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def show
    @categories = Category.all
    @books = @category.books
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:edit, :update, :destroy]
  def index
    @publishers = Publisher.all
  end

  def new
    @page_title = 'Add New Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = 'Publisher Successfully Created!'
      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @publisher.update(publisher_params)
      flash[:notice] = "Publisher Successfully Updated!"
      redirect_to publishers_path
    else
      render 'edit'
    end
  end

  def destroy
    @publisher.destroy
    flash[:alert] = "Publisher Removed!"
    redirect_to publishers_path
  end

  private

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.haml
%h1= @page_title
%p
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/authors/edit.html.haml
%h2 Edit Author
= render 'shared/forms/author'

app/views/authors/index.html.haml
%h2 Authors

%table.table.table-striped
  %tr
    %th Author Name
    %th Actions
  - @authors.each do |author|
    %tr
      %td
        = author.first_name
        = author.last_name
      %td
        = link_to 'Edit', edit_author_path(author.id)
        | #{link_to 'Delete', author_path(author), method: :delete, data: { confirm: 'Are you sure?' }}

app/views/authors/new.html.haml
%h2 Add New Author
= render 'shared/forms/author'

app/views/books/edit.html.haml
%h2 Edit Book
= render 'shared/book'

app/views/books/index.html.haml
= render 'shared/books'

app/views/books/new.html.haml
%h2 Add a New Book
= render 'shared/forms/book'

app/views/books/show.html.haml
#books-show
  %h2= @book.title
  .books-show-left
    = image_tag(@book.cover_path)
  .books-show-right
    %h3 Book Info:
    %ul
      %li
        %strong Category:
        = @book.category.name
      %li
        %strong Author:
        = @book.author.first_name
        = @book.author.last_name
      %li
        %strong Publisher
        = @book.publisher.name
      %li
        %strong Year:
        = @book.year
      %li
        %strong ISBN:
        = @book.isbn
      %li
        %strong Format:
        = @book.format
      %li
        %strong Pages:
        = @book.pages

    = link_to 'Buy for ' + @book.price, @book.buy, class: 'btn btn-success', target: '_blank'

  .clearfix
  %h4 Excerpt
  = simple_format(@book.excerpt)

  %h3 Available Actions
  = link_to 'Edit', edit_book_path(@book.id)
  | #{link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Are you sure?'}}

app/views/categories/edit.html.haml
%h2 Edit Category
= render 'shared/forms/category'

app/views/categories/index.html.haml
%h2 Categories

%table.table.table-striped
  %tr
    %th Category Name
    %th Actions
  - @categories.each do |category|
    %tr
      %td= category.name
      %td
        = link_to 'Edit', edit_category_path(category.id)
        | #{link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }}

app/views/categories/new.html.haml
%h2 Add New Category
= render 'shared/forms/category'

app/views/categories/show.html.haml
%h2= @category.name
= render 'shared/books'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title
      = @page_title ? @page_title : 'Welcome'
      | My Bookstore
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{:class => "#{params[:controller] == 'books' ? 'active' : ''}"}
              =link_to 'Home', root_path
            %li{:class => "#{params[:controller] == 'about' ? 'active' : ''}"}
              =link_to 'About', about_path
          %ul.nav.navbar-nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Add New
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'Book', new_book_path
                %li= link_to 'Category', new_category_path
                %li= link_to 'Author', new_author_path
                %li= link_to 'Publisher', new_publisher_path

            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Manage
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'Categories', categories_path
                %li= link_to 'Authors', authors_path
                %li= link_to 'Publishers', publishers_path
    %header
      .container
        %h1
          My Bookstore
          %small= @page_title ? @page_title : 'Welcome'
    %section
      .container
        .row
          .col-md-8
            - if flash[:notice]
              .alert.alert-success= flash[:notice]
            - if flash[:alert]
              .alert.alert-danger= flash[:alert]
            = yield
          .col-md-4
            =render 'shared/sidebar'
    %footer
      .container
        Copyright by Jakub Oblizajek 2017 &copy;

app/views/publishers/edit.html.haml
%h2 Edit publisher
= render 'shared/forms/publisher'

app/views/publishers/index.html.haml
%h1 Publishers
%table.table.table-striped
  %tr
    %th Publisher Name
    %th Actions
  - @publishers.each do |publisher|
    %tr
      %td= publisher.name
      %td
        = link_to 'Edit', edit_publisher_path(publisher.id)
        | #{link_to 'Delete', publisher_path(publisher), method: :delete, data: { confirm: 'Are you sure?' }}

app/views/publishers/new.html.haml
%h2 Add New Publisher
= render 'shared/forms/publisher'

app/views/shared/_bookform.html.haml
= form_for @book do |f|
  = render 'shared/errors', object: @book
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :isbn, 'ISBN'
    = f.text_field :isbn, class: 'form-control'

  .form-group
    = f.label :category
    = f.select :category_id, Category.all.collect { |x| [x.name, x.id]}, {include_blank: 'Select One'}, class: 'form-control'

  .form-group
    = f.label :author
    = f.select :author_id, Author.all.collect { |x| [x.first_name + ' ' + x.last_name, x.id]}, {include_blank: 'Select One'}, class: 'form-control'

  .form-group
    = f.label :publisher
    = f.select :publisher_id, Publisher.all.collect { |x| [x.name, x.id]}, {include_blank: 'Select One'}, class: 'form-control'

  .form-group
    = f.label :format
    = f.text_field :format, class: 'form-control'

  .form-group
    = f.label :year
    = f.number_field :year, class: 'form-control'

  .form-group
    = f.label :cover_path
    = f.text_field :cover_path, class: 'form-control'

  .form-group
    = f.label :excerpt
    = f.text_area :excerpt, class: 'form-control'

  .form-group
    = f.label :pages
    = f.number_field :pages, class: 'form-control'

  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  .form-group
    = f.label :buy
    = f.url_field :buy, class: 'form-control'

  = f.submit 'Submit', class: 'btn btn-primary'
  = link_to 'Back', books_path, class: 'btn btn-default'

app/views/shared/_books.html.haml
#books-index
  - @books.each_slice(4) do |book|
    .row
      - book.each do |book|
        .col-md-3.col-sm-3
          %h3= book.title
          = image_tag(book.cover_path)
          = link_to 'Read More', book_path(book), class: 'btn btn-primary'

app/views/shared/_errors.html.haml
- if object.errors.any?
  - object.errors.full_messages.each do |msg|
    .alert.alert-danger= msg

app/views/shared/_sidebar.html.haml
- if params[:controller] == 'about'
  .well
    %h3 Location Info
    %ul
      %li My Bookstore
      %li 234 Krakow Street
      %li Warsaw
      %li Phone: (123) 456 789
      %li Email: support@mybookstore.com

- if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show'
  .list-group
    - @categories.each do |category|
      = link_to category.name, category_path(category.id), class: 'list-group-item'

app/views/shared/forms/_author.html.haml
= form_for @author do |f|
  = render 'shared/errors', object: @author
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control', autofocus: true

  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'

  = f.submit 'Submit', class: 'btn btn-primary'
  = link_to 'Back', authors_path, class: 'btn btn-default'

app/views/shared/forms/_book.html.haml
= form_for @book do |f|
  = render 'shared/errors', object: @book
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', autofocus: true

  .form-group
    = f.label :isbn, 'ISBN'
    = f.text_field :isbn, class: 'form-control'

  .form-group
    = f.label :category
    = f.select :category_id, Category.all.collect { |x| [x.name, x.id]}, {include_blank: 'Select One'}, class: 'form-control'

  .form-group
    = f.label :author
    = f.select :author_id, Author.all.collect { |x| [x.first_name + ' ' + x.last_name, x.id]}, {include_blank: 'Select One'}, class: 'form-control'

  .form-group
    = f.label :publisher
    = f.select :publisher_id, Publisher.all.collect { |x| [x.name, x.id]}, {include_blank: 'Select One'}, class: 'form-control'

  .form-group
    = f.label :format
    = f.text_field :format, class: 'form-control'

  .form-group
    = f.label :year
    = f.number_field :year, class: 'form-control'

  .form-group
    = f.label :cover_path
    = f.text_field :cover_path, class: 'form-control'

  .form-group
    = f.label :excerpt
    = f.text_area :excerpt, class: 'form-control'

  .form-group
    = f.label :pages
    = f.number_field :pages, class: 'form-control'

  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  .form-group
    = f.label :buy
    = f.url_field :buy, class: 'form-control'

  = f.submit 'Submit', class: 'btn btn-primary'
  = link_to 'Back', books_path, class: 'btn btn-default'

app/views/shared/forms/_category.html.haml
= form_for @category do |f|
  = render 'shared/errors', object: @category
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', autofocus: true

  = f.submit 'Submit', class: 'btn btn-primary'
  = link_to 'Back', categories_path, class: 'btn btn-default'

app/views/shared/forms/_publisher.html.haml
= form_for @publisher do |f|
  = render 'shared/errors', object: @publisher
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', autofocus: true

  = f.submit 'Submit', class: 'btn btn-primary'
  = link_to 'Back', publishers_path, class: 'btn btn-default'